### Register a new user
POST http://localhost:5066/api/auth/register
Content-Type: application/json

{
    "username": "elifdeneme4",
    "email": "elifdeneme4@example.com",
    "password": "Password123!"
}
