### 1. Register a new user (Yeni bir kullanıcı kaydet)
POST http://localhost:5066/api/auth/register
Content-Type: application/json

{
    "username": "elifTestKullanici12",
    "email": "elifTest12@example.com",
    "password": "Password123!"
}

### -----------------------------------------------------
### 2. Login an existing user (Mevcut bir kullanıcı ile giriş yap)
POST http://localhost:5066/api/auth/login
Content-Type: application/json

{
    "email": "elifTest12@example.com",  
    "password": "Password123!"          
}
